"""empty message

Revision ID: 611634c18f21
Revises: c49c8f640fd1
Create Date: 2025-07-17 11:15:42.137931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611634c18f21'
down_revision = 'c49c8f640fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
