"""empty message

Revision ID: 967345705c91
Revises: 697370c4aa26
Create Date: 2025-07-16 19:04:48.648411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967345705c91'
down_revision = '697370c4aa26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('slogan', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videojuego')
    op.drop_table('empresa')
    # ### end Alembic commands ###
